import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Game Database',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAQCAYAAADJViUEAAABL0lEQVR4AWKAAYFqQONkCRRhFEXhH3eHjkOk4z3isJu3D9IDDomIS8b64NLxHtiKu3535uzMm5c2fHPn2PrmG5kQhhN4hT9dND45BP7ISIQsaIAhOIVnXTQ+uXqBERtWwxz0Qqq8ImjWDeT3Aj36GmfCGvzBC4xANjivDI2v/E/9TAva4dFMcQ+t3hiNr4767RZsmOGwAlneOEu+29uw4NYxbqBWg2Lo1Q3kk6vLzswviU+IOMM1ZWvSgXJ69MnM+JbYhXzIhUX4lc9F4yvflf9t4yh8QS8kwpjzgAKNr7xX/aiNt+EcSqAHnjTwwSenp/52IGMayuDCH7koL1O/x8Z5UAcDVoiDAfXzbBxjJr4xPW3ccQ1swrtXFvjk6gWG/88qgAgcwSP86qLxyd3hP42YDW0mUmX7AAAAAElFTkSuQmCC" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
